### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by hamstar** [hamstar/Wikimate#29]
I just want to say thanks to @samwilson @waldyrious @MhdSyrwan and @Chillibear for all your help keeping this project alive in my absence, and to all the people who have done pull requests. It's really awesome :+1:

**Comment by waldyrious** [comment]
It's the beauty of open source and a permissive collaboration model :) so thanks for the trust in the first place!

**Comment by samwilson** [comment]
Gosh, yes, thank *you* @hamstar! It's so great to find projects that one can build upon. I love finding opensource things that do 90% of what I want, and am always happy to help add the extra bits and bobs. :-)

**Comment by MhdSyrwan** [comment]
Thank you too @hamstar. Actually, I haven't contributed to this repository :disappointed:  since the time i left PHP.

I want to say thank you again :+1:  to @samwilson @waldyrious for maintaining the project and keeping it alive ! 

And like what others said, it's all about the open source culture/model.
