### ISSUE TITLE
Improvements to section processing

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#31]
The section processing in getText (from the preg_match_all down) has some problems:

1. The regex (rightly marked with a TODO) can be improved so that it matches headers with a symmetric number of ='s, and those that happen to have spaces behind them.
1. The last section (both by index and by name) isn't given a length in the sections arrays. getSection works around this but it's not elegant.
1. Pages with duplicate section headers (see e.g. [Item](https://doomwiki.org/wiki/Item)) result in fewer byName entries than byIndex, and incorrect offset / negative length values in both.

I have code changes for these ready, but would like to understand (from a commit organizational perspective) whether these are better applied in a separate branch & PR or could also hitchhike along in the ongoing patch-1 of PR #30. Thoughts?

**Comment by waldyrious** [comment]
I personally would prefer these as a separate PR. The thread in #30 is long enough already :)

**Comment by Xymph** [comment]
That was my thinking too, so thanks a lot for wrapping that one up.

I'm assuming I can continue to use my patch-1 branch for the commits in this issue? Or should it be deleted now, and new one started?
If the latter, I can use the Delete button in the previous PR, but how do I then sync my local git tree?
As an aside, I've been wondering why the Branch dropdown list on the main page never listed patch-1?

Further, can I simply create a new branch from the command line and commit changes referencing this issue number? Or should I create a new pull request? I must admit still being a little confused about GitHub's mix of web GUI and command-line approaches to the same repo's, and I have found little in their Help and Guides sections to clarify the latter.

**Comment by waldyrious** [comment]
> I'm assuming I can continue to use my patch-1 branch for the commits in this issue? Or should it be deleted now, and new one started?

Normally people tend to delete the branch and start a new one, but that's just a convention. In semantic terms, it makes more sense for new branches to be based off master (i.e. the merge commit that has `patch-1` and the previous commit on `master` as parents, rather than the last commit of `patch-1` before the merge). But in technical terms it doesn't really make much of a difference (well, it may make eventual rebases easier, but I never attempted that.)

To play it safe, I'd suggest starting a new one. If you delete it on github and start the new one on github as well, after the deletion, it will be called `patch-1` too, but only the name will be the same -- it will have no connection with the previous branch. If however you want to give it a more specific name, you'll have to create it in the command line and then sync with your fork with `push --set-upstream origin branchname` (the upstream branchname can be different from the local one, but it's convenient to keep them the same). You only need to use `--set-upstream` once; after that, plain `git push` will know which upstream branch to sync.

> If the latter, I can use the Delete button in the previous PR, but how do I then sync my local git tree?

To sync your local clone of your fork (and then your fork too, which weirdly isn't possible from the web interface), you will have to add another remote to the repo. Normally the default remote is `origin`, corresponding to your fork, so I usually call the one corresponding to the canonical repo `upstream`.

> As an aside, I've been wondering why the Branch dropdown list on the main page never listed patch-1?

That's because branches from forks are not actually created in the original repo; only internal git references are created, which are read-only. This used to be a pain point when a PR became abandoned, since the branch in the PR couldn't be changed by the project maintainers to get the PR into a mergeable state, since it only existed as a branch in the fork, where the maintainers didn't have commit access -- so separate PRs had to be started, and the existing ones closed, which was a mess. They [recently changed this](https://github.com/blog/2247-improving-collaboration-with-forks), but by allowing fork authors to give commit rights to the upstream maintainers (maybe just in the PR branch? I haven't played with that functionality enough to know), rather than creating the PR branches in the original repo. Which means that `patch-1` *still* won't appear in the dropdown, at least for the time being.

> Further, can I simply create a new branch from the command line and commit changes referencing this issue number? Or should I create a new pull request?

Both, actually. If you create a local branch, and push it you your fork, when visiting your fork you'll see a box mentioning recently pushed branches, with a green "create pull request" button.

> I must admit still being a little confused about GitHub's mix of web GUI and command-line approaches to the same repo's, and I have found little in their Help and Guides sections to clarify the latter.

You're not the only one :( I think they've been making some strides recently in getting the web UI more fuctional for the basic operations (non-interactive rebasing and conflict resolution is an obvious next candidate IMO), but we can only wait.

----

Ok, so to sum up: delete the branch on the previous PR; add the upstream repo to your fork (`git remote add upstream https://github.com/hamstar/Wikimate.git`); get the merge commit (`git checkout master && git pull`); create a new branch (`git checkout -b new-branch-name`) and send it to your fork (`git push --set-upstream origin new-branch-name`). On the web interface, create a pull request based on that branch (the button should only appear if the branch actually has commits above master). From then on, you can make any changes to the branch locally, and a `git push` (with `--force` if necessary) will update the branch in your fork on github, and therefore on the PR as well.

**Comment by Xymph** [comment]
Thanks much for elaborating and for the detailed instructions. FYI `fetch --prune` did not delete the branch, `branch -D` was needed. Everything else went according to recipe. :)
Given that cli git is needed for many non-trivial actions, I'd rather use one interface all the time, but I gather the website remains necessary for some steps central to GitHub (most notably pull requests). That's understandable but I guess I'm not alone in struggling to grasp all that, so I'm really glad an experienced collaborator like yourself is active on this repository to guide (relative) newbies like me along. :+1:

**Comment by waldyrious** [comment]
There's actually a way to do it all in the command line -- github's [own](https://github.com/github/hub#git--hub--github) [`hub`](https://hub.github.com/) [command](https://hub.github.com/hub.1.html) line tool-- but I haven't had the opportunity to improve the [tldr instructions](https://tldr.ostera.io/hub) for it. If you'd like to give that a try, please let me know of any improvements you'd suggest to those instructions in order to make them clearer.

**Comment by waldyrious** [comment]
Fixed in #33.

**Comment by Xymph** [comment]
Hmm, it requires git v1.7.3 but I'm on 1.7.1 (SciLinux 6.8). Anyway, I'll keep trying and learning, and asking if necessary. :smile:

**Comment by waldyrious** [comment]
👍 this also helps me stay sharp on my own learning :)
